version: '3'

services:
  bazel:
    image: tradingai/bazel:latest
    command:
      /bin/bash /root/go/src/github.com/tradingAI/tweb/docker-compose.sh
    volumes:
      - .:/root/go/src/github.com/tradingAI/tweb/
  grandet_db:
    image: postgres:11.1
    environment:
      POSTGRES_PASSWORD: ${TWEB_POSTGRES_PASSWORD}
      POSTGRES_USER: ${TWEB_POSTGRES_USER}
      POSTGRES_DB: ${TWEB_POSTGRES_DB}
    container_name: tweb_db
    ports:
      - ${TWEB_POSTGRES_PORT}:5432
    volumes:
      - /tmp/tweb_db/pgdata:/var/lib/postgresql/data
  minio:
    image: minio/minio:latest
    ports:
      - ${TWEB_MINIO_PORT}:9000
    environment:
      MINIO_ACCESS_KEY: ${TWEB_MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${TWEB_MINIO_SECRET_KEY}
    container_name: tweb_minio
    volumes:
      - /tmp/tweb/minio/data:/data
    command: ["server", "/data"]
  tweb:
    image: registry.cn-hangzhou.aliyuncs.com/tradingai/tweb:latest
    container_name: tweb_app
    environment:
      TUSHARE_TOKEN: ${TUSHARE_TOKEN}
      TUSHARE_API: https://api.tushare.pro
      TWEB_POSTGRES_HOST: ${TWEB_POSTGRES_HOST}
      TWEB_POSTGRES_PORT: ${TWEB_POSTGRES_PORT}
      TWEB_POSTGRES_RECONNECT_SEC: ${TWEB_POSTGRES_RECONNECT_SEC}
      TWEB_POSTGRES_PASSWORD: ${TWEB_POSTGRES_PASSWORD}
      TWEB_POSTGRES_USER: ${TWEB_POSTGRES_USER}
      TWEB_POSTGRES_DB: ${TWEB_POSTGRES_DB}
      TWEB_POSTGRES_RESET: ${TWEB_POSTGRES_RESET}
      TWEB_MINIO_ACCESS_KEY: ${TWEB_MINIO_ACCESS_KEY}
      TWEB_MINIO_SECRET_KEY: ${TWEB_MINIO_SECRET_KEY}
      TWEB_MINIO_HOST: ${TWEB_MINIO_HOST}
      TWEB_MINIO_PORT: ${TWEB_MINIO_PORT}
      TWEB_MINIO_SECURE: ${TWEB_MINIO_SECURE}
      TWEB_RECORD_CODE: ${TWEB_RECORD_CODE}
      TWEB_RECORD_URL: ${TWEB_RECORD_URL}
      TWEB_CREATE_ADMIN: ${TWEB_CREATE_ADMIN}
      TWEB_ADMIN_USERNAME: ${TWEB_ADMIN_USERNAME}
      TWEB_ADMIN_PASSWORD: ${TWEB_ADMIN_PASSWORD}
      TWEB_PORT: ${TWEB_PORT}
      TWEB_CROS_ALLOW_ORIGINS: http://localhost:3030
      TWEB_STORAGE_DIR: ${TWEB_STORAGE_DIR}
    ports:
      - ${TWEB_PORT}:${TWEB_PORT}
    depends_on:
      - grandet_db
      - minio
    restart: always
    volumes:
      - ./:/go/src/github.com/tradingAI/tweb
