// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FetchAccountRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchAccountRequest) Reset()         { *m = FetchAccountRequest{} }
func (m *FetchAccountRequest) String() string { return proto.CompactTextString(m) }
func (*FetchAccountRequest) ProtoMessage()    {}
func (*FetchAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}

func (m *FetchAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchAccountRequest.Unmarshal(m, b)
}
func (m *FetchAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchAccountRequest.Marshal(b, m, deterministic)
}
func (m *FetchAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchAccountRequest.Merge(m, src)
}
func (m *FetchAccountRequest) XXX_Size() int {
	return xxx_messageInfo_FetchAccountRequest.Size(m)
}
func (m *FetchAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchAccountRequest proto.InternalMessageInfo

type FetchAccountResponse struct {
	Error                Error    `protobuf:"varint,1,opt,name=error,proto3,enum=common.Error" json:"error,omitempty"`
	Accounts             []*User  `protobuf:"bytes,2,rep,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchAccountResponse) Reset()         { *m = FetchAccountResponse{} }
func (m *FetchAccountResponse) String() string { return proto.CompactTextString(m) }
func (*FetchAccountResponse) ProtoMessage()    {}
func (*FetchAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{1}
}

func (m *FetchAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchAccountResponse.Unmarshal(m, b)
}
func (m *FetchAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchAccountResponse.Marshal(b, m, deterministic)
}
func (m *FetchAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchAccountResponse.Merge(m, src)
}
func (m *FetchAccountResponse) XXX_Size() int {
	return xxx_messageInfo_FetchAccountResponse.Size(m)
}
func (m *FetchAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FetchAccountResponse proto.InternalMessageInfo

func (m *FetchAccountResponse) GetError() Error {
	if m != nil {
		return m.Error
	}
	return Error_NO_ERROR
}

func (m *FetchAccountResponse) GetAccounts() []*User {
	if m != nil {
		return m.Accounts
	}
	return nil
}

type CreateAccountRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountRequest) Reset()         { *m = CreateAccountRequest{} }
func (m *CreateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAccountRequest) ProtoMessage()    {}
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{2}
}

func (m *CreateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountRequest.Unmarshal(m, b)
}
func (m *CreateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountRequest.Marshal(b, m, deterministic)
}
func (m *CreateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountRequest.Merge(m, src)
}
func (m *CreateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAccountRequest.Size(m)
}
func (m *CreateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountRequest proto.InternalMessageInfo

func (m *CreateAccountRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateAccountRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreateAccountResponse struct {
	Error                Error    `protobuf:"varint,1,opt,name=error,proto3,enum=common.Error" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountResponse) Reset()         { *m = CreateAccountResponse{} }
func (m *CreateAccountResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAccountResponse) ProtoMessage()    {}
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{3}
}

func (m *CreateAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountResponse.Unmarshal(m, b)
}
func (m *CreateAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountResponse.Marshal(b, m, deterministic)
}
func (m *CreateAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountResponse.Merge(m, src)
}
func (m *CreateAccountResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAccountResponse.Size(m)
}
func (m *CreateAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountResponse proto.InternalMessageInfo

func (m *CreateAccountResponse) GetError() Error {
	if m != nil {
		return m.Error
	}
	return Error_NO_ERROR
}

type UpdateAccountRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAccountRequest) Reset()         { *m = UpdateAccountRequest{} }
func (m *UpdateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAccountRequest) ProtoMessage()    {}
func (*UpdateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{4}
}

func (m *UpdateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAccountRequest.Unmarshal(m, b)
}
func (m *UpdateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAccountRequest.Marshal(b, m, deterministic)
}
func (m *UpdateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAccountRequest.Merge(m, src)
}
func (m *UpdateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAccountRequest.Size(m)
}
func (m *UpdateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAccountRequest proto.InternalMessageInfo

func (m *UpdateAccountRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateAccountRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type UpdateAccountResponse struct {
	Error                Error    `protobuf:"varint,1,opt,name=error,proto3,enum=common.Error" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAccountResponse) Reset()         { *m = UpdateAccountResponse{} }
func (m *UpdateAccountResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateAccountResponse) ProtoMessage()    {}
func (*UpdateAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{5}
}

func (m *UpdateAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAccountResponse.Unmarshal(m, b)
}
func (m *UpdateAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAccountResponse.Marshal(b, m, deterministic)
}
func (m *UpdateAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAccountResponse.Merge(m, src)
}
func (m *UpdateAccountResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateAccountResponse.Size(m)
}
func (m *UpdateAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAccountResponse proto.InternalMessageInfo

func (m *UpdateAccountResponse) GetError() Error {
	if m != nil {
		return m.Error
	}
	return Error_NO_ERROR
}

type DeleteAccountRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAccountRequest) Reset()         { *m = DeleteAccountRequest{} }
func (m *DeleteAccountRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAccountRequest) ProtoMessage()    {}
func (*DeleteAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{6}
}

func (m *DeleteAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAccountRequest.Unmarshal(m, b)
}
func (m *DeleteAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAccountRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAccountRequest.Merge(m, src)
}
func (m *DeleteAccountRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAccountRequest.Size(m)
}
func (m *DeleteAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAccountRequest proto.InternalMessageInfo

func (m *DeleteAccountRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteAccountResponse struct {
	Error                Error    `protobuf:"varint,1,opt,name=error,proto3,enum=common.Error" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAccountResponse) Reset()         { *m = DeleteAccountResponse{} }
func (m *DeleteAccountResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteAccountResponse) ProtoMessage()    {}
func (*DeleteAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{7}
}

func (m *DeleteAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAccountResponse.Unmarshal(m, b)
}
func (m *DeleteAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAccountResponse.Marshal(b, m, deterministic)
}
func (m *DeleteAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAccountResponse.Merge(m, src)
}
func (m *DeleteAccountResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteAccountResponse.Size(m)
}
func (m *DeleteAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAccountResponse proto.InternalMessageInfo

func (m *DeleteAccountResponse) GetError() Error {
	if m != nil {
		return m.Error
	}
	return Error_NO_ERROR
}

func init() {
	proto.RegisterType((*FetchAccountRequest)(nil), "account.FetchAccountRequest")
	proto.RegisterType((*FetchAccountResponse)(nil), "account.FetchAccountResponse")
	proto.RegisterType((*CreateAccountRequest)(nil), "account.CreateAccountRequest")
	proto.RegisterType((*CreateAccountResponse)(nil), "account.CreateAccountResponse")
	proto.RegisterType((*UpdateAccountRequest)(nil), "account.UpdateAccountRequest")
	proto.RegisterType((*UpdateAccountResponse)(nil), "account.UpdateAccountResponse")
	proto.RegisterType((*DeleteAccountRequest)(nil), "account.DeleteAccountRequest")
	proto.RegisterType((*DeleteAccountResponse)(nil), "account.DeleteAccountResponse")
}

func init() { proto.RegisterFile("account.proto", fileDescriptor_8e28828dcb8d24f0) }

var fileDescriptor_8e28828dcb8d24f0 = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xbf, 0x6b, 0xc3, 0x30,
	0x10, 0x85, 0x89, 0x42, 0xdb, 0xf4, 0x9a, 0x64, 0x70, 0x1d, 0x08, 0x59, 0x9a, 0xaa, 0x50, 0x3c,
	0xc5, 0x90, 0xae, 0x5d, 0x92, 0xfe, 0x80, 0x2e, 0x1d, 0x04, 0x59, 0xba, 0xc9, 0xd6, 0x91, 0x18,
	0x6a, 0xc9, 0x3d, 0xc9, 0xe4, 0xdf, 0x2f, 0xb2, 0x9d, 0x80, 0xdd, 0xa1, 0x78, 0x32, 0x77, 0xdf,
	0xf9, 0xbd, 0x6f, 0x10, 0x4c, 0x64, 0x9a, 0x9a, 0x52, 0xbb, 0x55, 0x41, 0xc6, 0x99, 0xe0, 0xaa,
	0x19, 0x17, 0xe3, 0xd4, 0xe4, 0xb9, 0xd1, 0xf5, 0x9a, 0xcf, 0xe0, 0xf6, 0x1d, 0x5d, 0x7a, 0xd8,
	0xd4, 0x54, 0xe0, 0x4f, 0x89, 0xd6, 0x71, 0x84, 0xb0, 0xbd, 0xb6, 0x85, 0xd1, 0x16, 0x83, 0x07,
	0xb8, 0x40, 0x22, 0x43, 0xf3, 0xc1, 0x72, 0x10, 0x4d, 0xd7, 0x93, 0x55, 0x13, 0xf6, 0xe6, 0x97,
	0xa2, 0x66, 0x41, 0x04, 0xa3, 0xa6, 0xcc, 0xce, 0xd9, 0x72, 0x18, 0xdd, 0xac, 0xc7, 0xa7, 0xbb,
	0x9d, 0x45, 0x12, 0x67, 0xca, 0x3f, 0x21, 0x7c, 0x21, 0x94, 0x0e, 0xdb, 0xf5, 0xc1, 0x02, 0x46,
	0xa5, 0x45, 0xd2, 0x32, 0xc7, 0xaa, 0xe9, 0x5a, 0x9c, 0x67, 0xcf, 0x0a, 0x69, 0xed, 0xd1, 0x90,
	0x9a, 0xb3, 0x9a, 0x9d, 0x66, 0xfe, 0x0c, 0xb3, 0x4e, 0x5e, 0x0f, 0x6f, 0xbe, 0x85, 0x70, 0x57,
	0xa8, 0xbf, 0x36, 0x53, 0x60, 0x99, 0xaa, 0xfe, 0x1c, 0x0a, 0x96, 0xa9, 0x96, 0x1d, 0x6b, 0xdb,
	0x79, 0x83, 0x4e, 0x46, 0x1f, 0x83, 0x47, 0x08, 0x5f, 0xf1, 0x1b, 0xff, 0x33, 0xf0, 0x2d, 0x9d,
	0xbb, 0x1e, 0x2d, 0xdb, 0xfb, 0xaf, 0xbb, 0x7d, 0xe6, 0x0e, 0x65, 0xe2, 0x69, 0xec, 0x48, 0xaa,
	0x4c, 0xef, 0x37, 0x1f, 0xb1, 0x3b, 0x62, 0x12, 0x57, 0xcf, 0x22, 0xb9, 0xac, 0x3e, 0x4f, 0xbf,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x25, 0xc9, 0x8f, 0xdb, 0x45, 0x02, 0x00, 0x00,
}
