// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stock.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FetchStockDailyRequest struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Start                int64    `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	End                  int64    `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchStockDailyRequest) Reset()         { *m = FetchStockDailyRequest{} }
func (m *FetchStockDailyRequest) String() string { return proto.CompactTextString(m) }
func (*FetchStockDailyRequest) ProtoMessage()    {}
func (*FetchStockDailyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c87a7814fbd674bd, []int{0}
}

func (m *FetchStockDailyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchStockDailyRequest.Unmarshal(m, b)
}
func (m *FetchStockDailyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchStockDailyRequest.Marshal(b, m, deterministic)
}
func (m *FetchStockDailyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchStockDailyRequest.Merge(m, src)
}
func (m *FetchStockDailyRequest) XXX_Size() int {
	return xxx_messageInfo_FetchStockDailyRequest.Size(m)
}
func (m *FetchStockDailyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchStockDailyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchStockDailyRequest proto.InternalMessageInfo

func (m *FetchStockDailyRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *FetchStockDailyRequest) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *FetchStockDailyRequest) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

type FetchStockDailyResponse struct {
	Error                Error         `protobuf:"varint,1,opt,name=error,proto3,enum=common.Error" json:"error,omitempty"`
	Dailys               []*StockDaily `protobuf:"bytes,2,rep,name=dailys,proto3" json:"dailys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *FetchStockDailyResponse) Reset()         { *m = FetchStockDailyResponse{} }
func (m *FetchStockDailyResponse) String() string { return proto.CompactTextString(m) }
func (*FetchStockDailyResponse) ProtoMessage()    {}
func (*FetchStockDailyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c87a7814fbd674bd, []int{1}
}

func (m *FetchStockDailyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchStockDailyResponse.Unmarshal(m, b)
}
func (m *FetchStockDailyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchStockDailyResponse.Marshal(b, m, deterministic)
}
func (m *FetchStockDailyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchStockDailyResponse.Merge(m, src)
}
func (m *FetchStockDailyResponse) XXX_Size() int {
	return xxx_messageInfo_FetchStockDailyResponse.Size(m)
}
func (m *FetchStockDailyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchStockDailyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FetchStockDailyResponse proto.InternalMessageInfo

func (m *FetchStockDailyResponse) GetError() Error {
	if m != nil {
		return m.Error
	}
	return Error_NO_ERROR
}

func (m *FetchStockDailyResponse) GetDailys() []*StockDaily {
	if m != nil {
		return m.Dailys
	}
	return nil
}

func init() {
	proto.RegisterType((*FetchStockDailyRequest)(nil), "stock.FetchStockDailyRequest")
	proto.RegisterType((*FetchStockDailyResponse)(nil), "stock.FetchStockDailyResponse")
}

func init() { proto.RegisterFile("stock.proto", fileDescriptor_c87a7814fbd674bd) }

var fileDescriptor_c87a7814fbd674bd = []byte{
	// 214 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x2e, 0xc9, 0x4f,
	0xce, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0xa4, 0x78, 0x92, 0xf3, 0x73,
	0x73, 0xf3, 0xf3, 0x20, 0x82, 0x4a, 0x21, 0x5c, 0x62, 0x6e, 0xa9, 0x25, 0xc9, 0x19, 0xc1, 0x20,
	0x39, 0x97, 0xc4, 0xcc, 0x9c, 0xca, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x21, 0x2e,
	0x96, 0xe4, 0xfc, 0x94, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x30, 0x5b, 0x48, 0x84,
	0x8b, 0xb5, 0xb8, 0x24, 0xb1, 0xa8, 0x44, 0x82, 0x49, 0x81, 0x51, 0x83, 0x39, 0x08, 0xc2, 0x11,
	0x12, 0xe0, 0x62, 0x4e, 0xcd, 0x4b, 0x91, 0x60, 0x06, 0x8b, 0x81, 0x98, 0x4a, 0x59, 0x5c, 0xe2,
	0x18, 0xa6, 0x16, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0x29, 0x73, 0xb1, 0xa6, 0x16, 0x15, 0xe5,
	0x17, 0x81, 0xcd, 0xe5, 0x33, 0xe2, 0xd5, 0x83, 0x3a, 0xc7, 0x15, 0x24, 0x18, 0x04, 0x91, 0x13,
	0xd2, 0xe2, 0x62, 0x4b, 0x01, 0xe9, 0x2a, 0x96, 0x60, 0x52, 0x60, 0xd6, 0xe0, 0x36, 0x12, 0x82,
	0xa9, 0x42, 0x32, 0x10, 0xaa, 0xc2, 0x49, 0x31, 0x4a, 0x3e, 0x3d, 0xb3, 0x24, 0xa3, 0x34, 0x09,
	0xa4, 0x46, 0xbf, 0xa4, 0x28, 0x31, 0x25, 0x33, 0x2f, 0xdd, 0xd1, 0x53, 0xbf, 0xa4, 0x3c, 0x35,
	0x49, 0x1f, 0xec, 0xc9, 0x24, 0x36, 0x30, 0x65, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xf5, 0xd8,
	0x60, 0xe2, 0x0f, 0x01, 0x00, 0x00,
}
